# -*- coding: utf-8 -*-
"""Copy of Student_AIChatbotsForEducation_Section3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O_hpY4r_dcABubFNI4_x9xnC-9pfJmN9

<font color="#de3023"><h1><b>REMINDER: MAKE A COPY OF THIS NOTEBOOK, DO NOT EDIT</b></h1></font>

# Notebook 3: Vector Stores, Chatbot Design, and Model Deployment


 ![Image](https://miro.medium.com/v2/resize:fit:1252/format:webp/1*TiLspsEC2D9db-9wioV-rw.jpeg)

Last time, we saw how to create a corpus of files that our assistants can use to provide relevant, specific responses.

 In this notebook, we'll see how we can *enhance* our assistants' ability to efficiently store and find files using a called a type of database called a vector store, giving it a bigger and faster memory.

Then, we'll brainstorm our assistants' goals and style, and examine ethical risks so we can plan useful guardrails. Finally, we'll create and deploy our chatbot assistants, so people can use them for their own personalized learning!

## Notebook Objectives
- **Enhance Searchable Memory**: Learn to enhance our assistants' memory using Vector Stores.
- **Deploy Your Chatbot**: Deploy our custom assistants on a web app, allowing users to upload their own files and interact with them!

By the end of this notebook, you will have a fully functional chatbot capable of understanding and answering queries based on a given corpus, deployed as a live web app! Hopefully you can use it as a study buddy, or at the very least, impress your parents and friends!
"""

#@title **🏗 Setup Cell** {"display-mode":"form", "form-width":"25%"}
#@markdown **Run this cell to import libraries and setup the environment!**

# ========================
# 📦 Install Dependencies
# ========================
!pip install -q openai
!apt-get -qq install git

# ========================
# 📚 Import Libraries
# ========================
import os, time, json, shutil, warnings, concurrent
import pandas as pd
from time import sleep
from openai import OpenAI
import openai
from google.colab import files
from IPython.display import display, Markdown, Latex, HTML

# ========================
# ⚙️ Environment Setup
# ========================
pd.set_option('display.max_colwidth', 150)
warnings.filterwarnings("ignore")

os.makedirs("/content/python_study_guide", exist_ok=True)
os.makedirs("/content/directory", exist_ok=True)

# ========================
# 📂 Corpus Setup
# ========================

GCS_BUCKET = "https://storage.googleapis.com/inspirit-ai-data-bucket-1/Data/AI%20Scholars/Sessions%206%20-%2010%20(Projects)/Project%20-%20AI%20Chatbots%20for%20Education"

DATASETS = [
  "Andrej-Kaparthy-Reading-List.zip",
  "classic_works.zip",
  "python_study_guide.zip"
]

for zip_name in DATASETS:
  zip_url = f"{GCS_BUCKET}/{zip_name}"
  local_zip = f"/content/{zip_name}"
  !wget -q -nc -O "{local_zip}" "{zip_url}"
  !unzip -q -n "{local_zip}" -d "/content"

# ========================
# ⏳ Utility Function
# ========================
wait_time = 1  # kept for compatibility; not used by the Responses API

# ========================
# ⚠️ Warnings Handling
# ========================
warnings.filterwarnings("ignore", category=DeprecationWarning)

# Helper: create a local assistant config (Responses API doesn't need a server-side object)
from types import SimpleNamespace

def make_assistant(name, instructions, tools=None):
    """Returns a simple object holding the assistant's name, instructions, and tools."""
    return SimpleNamespace(name=name, instructions=instructions, tools=tools or [])

"""## Understanding Vector Stores 🗄️


In our last notebook, we converted our files into embeddings (lists of numbers) and used cosine similarity to identify the most similar (i.e relevant) files for a given search term by comparing each file to the search term individually.

**Discuss**: What problem could arise here if we have a lot of files?

If we want our chatbots to be able to store a lot of information and be able to find important files quickly, we need a more efficient system.

Instead of comparing file embeddings individually, we can use Vector Stores to store and search them efficiently.


### What is a Vector Store?

A *vector store* is a special database for storing and finding vectors efficiently, using the following steps:

- **Convert Text to Numbers**: First, the data (such as text files) is converted to vectors (lists of numbers) using embedding techniques like we saw last time.
- **Indexing**: Then, the vector store organizes these vectors in an optimized way, so they're easy to lookup quickly at scale. Imagine sorting books in a library by section, so it's easier to find a specific book.
- **Querying**: Finally, when you ask your assistant a question, the vector store uses specialized algorithms to quickly find the most similar files. These methods use the optimized storage to find files much faster (without having to compared every file)!

[![Screenshot-2025-03-16-at-21-40-13.png](https://i.postimg.cc/RZpJ1Swv/Screenshot-2025-03-16-at-21-40-13.png)](https://postimg.cc/NKT0BwNn)


In summary, vector stores efficiently store and organize vector data using optimized indexing methods to quickly lookup relevant files at scale. This can give our assistants a much larger and faster searchable memory to answer specific questions!

(Note: In addition to chatbots, vector stores can be used to store and search data for other powerful AI uses like recommendation systems, search engines, and content clustering.)

## Using Vector Stores with Our Assistant

Now let's wire up a vector store to our assistant using the Responses API's `file_search` tool. Fill in your API key below and remember to keep it secret.
"""

# Commented out IPython magic to ensure Python compatibility.
#@title {"display-mode":"form", "form-width":"25%"}
#@markdown Enter your secret API key below, and save it in a safe place on your computer!
api_key = "test" # @param {"type":"string"}
api_key = api_key.strip()

# %env OPENAI_API_KEY = {api_key}
client = OpenAI(api_key=api_key)
model = "gpt-4o-mini"

"""### Step 1. Define Our Assistant

Instead of creating a server-side assistant object, we define a local assistant configuration using `make_assistant()`. We'll add the `file_search` tool when we call `client.responses.create()` in Step 4.

"""

assistant = make_assistant(
  name="Zack's Helpful Paper Reader",  # TO:D0: Change your assistant name (including your name)
  instructions="You are a helpful assistant. Use your vector-store files to answer questions. Provide clear, accurate, and well-supported responses and citations",
)

"""Once the `file_search` tool is included in a response call, the model will automatically decide when to search your files based on the user's message. Next, let's set up the vector store the assistant will search from!

### Step 2. Create the Vector Store
As we've seen, vector stores are structures for storing and finding vectors efficiently.

Let's set up a vector store for our Helpful Paper Reader assistant to search and use academic papers. We'll store embeddings of text documents (e.g., PDFs), created using a language model to convert text into meaningful vectors, just like in our last notebook.

First, give your new vector store a name (to help keep track of it). You can name it whatever you like, but pick something relevant to what the vector store is for (e.g. "Paper Assistant Store").
"""

# Set the vector store name
vector_store_name = "Paper Assistant Store" # FILL IN HERE

# Create the vector store with the given name
vector_store = client.vector_stores.create(name=vector_store_name)

"""### Step 3. Upload Data to the Vector Store

Let's load data into our vector store! You can use the provided default corpus files provided or upload your own (try with one or two to start).

OpenAI's `file_search` tool supports `.pdf`,`.docx`, `.pptx`, and `.txt` (not CSV/Excel). (See the full [list here](https://platform.openai.com/docs/assistants/tools/file-search/supported-files#supported-files).)
"""

#@title {"display-mode":"form", "form-width":"25%"}
# @markdown Choose from the dropdown below!
corpus = "Upload your files!" # @param ["Choose your corpus!", "Upload your files!", "Andrej Kaparthy Reading List","Python Mastery Study Guide"]

if corpus == "Upload your files!":
# Move uploaded files to the created directory
  uploaded = files.upload()
  for filename in uploaded.keys():
    shutil.move(filename, '/content/directory/' + filename)

if corpus == "Andrej Kaparthy Reading List":

  source_dir = '/content/Andrej-Kaparthy-Reading-List'
  destination_dir = "/content/directory"

  for filename in os.listdir(source_dir):
      if filename.lower().endswith('.pdf'):
        source_file = os.path.join(source_dir, filename)
        destination_file = os.path.join(destination_dir, filename)
        shutil.move(source_file, destination_file)

if corpus == "Python Mastery Study Guide":
  source_dir = '/content/python_study_guide'
  destination_dir = "/content/directory"

  for filename in os.listdir(source_dir):
    if filename.lower().endswith('.pdf'):
        source_file = os.path.join(source_dir, filename)
        destination_file = os.path.join(destination_dir, filename)
        shutil.move(source_file, destination_file)

"""Nice job choosing files for your assistant! Run the next cell to upload the files to your new vector store."""

# @title Run to upload your corpus to the vector store {"display-mode":"form", "form-width":"25%"}

directory = "/content/directory"

# Create the vector store
vector_store = client.vector_stores.create(name=vector_store_name)

SUPPORTED = ('.pdf', '.docx', '.pptx', '.txt')

# Only non-empty, supported files (file_search rejects empty files and CSV/Excel)
file_paths = [
    os.path.join(directory, fn)
    for fn in os.listdir(directory)
    if os.path.isfile(os.path.join(directory, fn))
    and fn.lower().endswith(SUPPORTED)
    and os.path.getsize(os.path.join(directory, fn)) > 0
]

if not file_paths:
    raise SystemExit(
        "No non-empty, supported files found in /content/directory. "
        "Upload at least one non-empty .pdf/.docx/.pptx/.txt and re-run."
    )

# Open all files as binary streams
file_streams = [open(path, "rb") for path in file_paths]

try:
    # Upload and poll the files as a batch to the vector store
    file_batch = client.vector_stores.file_batches.upload_and_poll(
        vector_store_id=vector_store.id,
        files=file_streams
    )

    # Print the batch upload status and file counts
    print("Upload batch status:", file_batch.status)
    print("File counts:", file_batch.file_counts)

finally:
    # Close all file streams to avoid resource leaks
    for fs in file_streams:
        fs.close()

"""Great job! Now we have a vector store with uploaded files, and an assistant that can search it using its linked `file_search` tool. Let's test it out!

## Testing our Vector Store-Based Assistant 📝

Now let's try asking our model a question using the information in the vector store!

We pass the user's message and the `file_search` tool (pointing at our vector store) directly to `client.responses.create()` — no threads or runs needed.

Fill in the input user message below:
"""

input_text = "What is the main idea of the Llama 2 paper?"

# Call the Responses API with file_search pointed at the vector store
response = client.responses.create(
    model=model,
    instructions=assistant.instructions,
    input=input_text,
    tools=[{"type": "file_search", "vector_store_ids": [vector_store.id]}],
)

# Extract and display the response text
print(response.output_text)

"""**Discuss:** How did the model respond? Did it use the information from your corpus? How could you get your model to use its corpus more?

### Get Assistant's Response Citations


Importantly, we can even get the model's citations for its messages, i.e. which files in the vector store the model used as sources for its response.

(Note: if the assistant didn't use its stored files for a given response, the citations will be empty. How can you prompt it to use them?)
"""

#@title Run this cell to get your assistant's citations {"display-mode":"form", "form-width":"25%"}

citations = {}
insertions = []

for item in response.output:
  if item.type == "message":
    for block in item.content:
      if block.type == "output_text":
        for i, ann in enumerate(block.annotations):
          if ann.type == "file_citation":
            insertions.append((ann.index, i, ann.filename))
            citations[i] = ann.filename

# Remove duplicate (index, filename) pairs, keep unique citation numbers
seen = set()
unique_insertions = []
for idx, i, fname in insertions:
  key = (idx, fname)
  if key not in seen:
    seen.add(key)
    unique_insertions.append((idx, i, fname))

output_text = response.output_text
for pos, i, _ in sorted(unique_insertions, reverse=True):
  output_text = output_text[:pos+1] + f"[{i}]" + output_text[pos+1:]

print(output_text)
print()
for idx in sorted(citations):
  print(f"[{idx}] {citations[idx]}")

"""**Discuss**: How might citations be useful for your assistant?

## Interacting with the Assistant

Let's combine everything in a function that takes user input, sends it to the assistant, and retrieves the response along with citations from the uploaded documents—all within a *loop* to enable an ongoing conversation.


We've provided this function below; feel free to look at the code and then try out your new assistant!
"""

# @title Run to define a function to talk to your new assistant with citations {"display-mode":"form", "form-width":"25%"}

def start_conversation(assistant):
  conversation_history = []

  print(f"Start chatting with {assistant.name}! Type 'exit' to end the conversation.")

  while True:
    input_text = input("👤 You:\n")
    print()

    if input_text.lower() == "exit":
      print("Ending the conversation.")
      break

    conversation_history.append({
      "role": "user",
      "content": input_text
    })

    response = client.responses.create(
      model=model,
      instructions=assistant.instructions,
      tools=[{"type": "file_search", "vector_store_ids": [vector_store.id]}],
      input=conversation_history,
    )

    # Find the message block with output text
    output_text = None
    annotations = []
    for block in response.output:
      if block.type == "message":
        for c in block.content:
          if c.type == "output_text":
            output_text = c.text
            annotations = c.annotations
            break
      if output_text:
        break

    if not output_text:
      print("(no text response found)")
      continue

    conversation_history.append({
      "role": "assistant",
      "content": output_text
    })

    # Process annotations
    citations = {}
    insertions = []
    seen = set()

    for ann in annotations:
      if ann.type == "file_citation":
        if ann.file_id not in citations:
          citations[ann.file_id] = (len(citations), ann.filename)
        key = (ann.index, ann.file_id)
        if key not in seen:
          seen.add(key)
          insertions.append((ann.index, citations[ann.file_id][0]))

    for pos, i in sorted(insertions, reverse=True):
      output_text = output_text[:pos+1] + f"[{i}]" + output_text[pos+1:]

    print("🤖 Assistant's Response:")
    print(output_text)
    print()

    if citations:
      print("References:")
      for _, (index, filename) in sorted(citations.items(), key=lambda x: x[1][0]):
        print(f"[{index}] {filename}")

    print()

# Try talking to your vector store-powered assistant!
start_conversation(assistant)  # Fill in your assistant (Hint: Check what variable it's saved in, in Step 1 earlier)!

"""## Export Your Project Files 📦

Now let's package your assistant for deployment. Run the cell below to save your assistant configuration (name, instructions, model, and vector store) and corpus files, then download the zip to your computer.

You'll upload this file in the **[Assistants App Deployment](https://inspiritai.co/assistants_app_deployment)** notebook to build and deploy your app.
"""

#@title Run to export your project files 📥 {"display-mode":"form", "form-width":"25%"}
import os, json, shutil
from google.colab import files

# Clear and recreate hf_export/ to avoid including leftover files from previous runs
if os.path.exists('hf_export'):
    shutil.rmtree('hf_export')
os.makedirs('hf_export')

# Save assistant config — vector store already created in this notebook
config = {
    'assistant_name': assistant.name,
    'assistant_instructions': assistant.instructions,
    'model': model,
    'vector_store_id': vector_store.id,
}
with open('hf_export/config.json', 'w') as f:
    json.dump(config, f, indent=2)
print('✅ config.json saved')

# Save requirements.txt
with open('hf_export/requirements.txt', 'w') as f:
    f.write('gradio\nopenai\n')
print('✅ requirements.txt saved')

# Zip and download
shutil.make_archive('project_export', 'zip', 'hf_export')
files.download('project_export.zip')
print('\n✅ project_export.zip downloaded!')

"""## Wrap Up 🏆

Congratulations — that's the end of this notebook! You've built a vector store-powered AI assistant with its own corpus, citations, and a custom personality. 🎉

**Next step:** open the **[Assistants App Deployment](https://inspiritai.co/assistants_app_deployment)** notebook to turn your assistant into a live web app anyone can use. 🚀
"""